name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  spring-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run backend tests and generate coverage
      run: mvn clean verify
      working-directory: ./back

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: back/target/surefire-reports/

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: back/target/surefire-reports/*.xml
        reporter: java-junit
