name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  spring-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run backend tests and generate coverage
      run: mvn clean verify
      working-directory: ./back

    # - name: Upload JaCoCo coverage report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: jacoco-report
    #     path: back/target/site/jacoco/
  
    - name: Generate JaCoCo Badge and Summary
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: back/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
