name: Angular and Spring Boot Tests

on:
  push:
    branches:
      - main 
  pull_request:
  
jobs:
 frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./front

        
      - name: Run frontend tests and generate coverage
        run: npm run test -- --code-coverage --browsers=ChromeHeadless --watch=false
        working-directory: ./front

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: angular-results
          path: front/coverage/

      - name: SonarQube Scan
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=TaigaProZz_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
            -Dsonar.organization=taigaprozz \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=front/src \
            -Dsonar.tests=front/src \
            -Dsonar.test.inclusions=front/src/**/*.spec.ts \
            -Dsonar.typescript.lcov.reportPaths=front/coverage/bobapp/lcov.info \
            -Dsonar.exclusions=front/src/polyfills.ts,front/src/environments/**/*.ts
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


 spring-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run tests and generate coverage
      run: mvn clean verify
      working-directory: ./back

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: springboot-results
        path: back/target/site/jacoco

    - name: SonarQube Scan
      working-directory: ./back
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=TaigaProZz_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
          -Dsonar.organization=taigaprozz \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=back/src/main/java \
          -Dsonar.tests=back/src/test/java \
          -Dsonar.junit.reportPaths=back/target/surefire-reports \
          -Dsonar.jacoco.reportPaths=back/target/jacoco.exec
        env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
